name: AI Solution Kit GH-Pages

on:
  push:
    branches:
      - main  # trigger main branch
    paths:
      - learn/**/*

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true

      - name: Build
        run: |
          cd learn
          hugo --minify
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public